:toc: macro
:toclevels: 5
:figure-caption!:

:core_link: link:https://trmnl.com[Core]
:image_magick_geometry_link: link:https://www.imagemagick.org/script/command-line-processing.php#geometry[ImageMagick Geometry]
:petail_link: link:https://alchemists.io/projects/petail[Petail]
:rodauth_link: link:https://rodauth.jeremyevans.net[Rodauth]
:trmnl_api_gem_link: link:https://github.com/usetrmnl/trmnl-api[TRMNL API]
:trmnl_firmware_link: link:https://github.com/usetrmnl/trmnl-firmware[TRMNL Firmware]

= API

The API is divided into two categories: Firmware and Server. The former is more stable and mimics what we use on the {core_link} server. The latter is still in development and is unique to Terminus only. The following sections detail each.

toc::[]

== Firmware

The following endpoints are used to communicate with your device's {trmnl_firmware_link}. These endpoints typically require authentication via the HTTP `ID` header which is your device's MAC address. Any changes to these endpoints require updates to both the firmware and this implementation so they don't change often.

=== Display

Used for displaying new content on your device via a HTTP GET request. These requests happen on a scheduled interval as determined by the `refresh_rate` (see the response example below).

In truth, the design of this API request should have been a POST request but the {trmnl_firmware_link} only uses GET requests at the moment. The reason is because each request includes header information which provides updates to device activity (such as WiFi signal strength, battery voltage, etc) that the server stores with the associated device. This means each request is an update from the device to the server while each response is a potential settings change from the server to the device.

.Request
[%collapsible]
====
[source,bash]
----
curl "https://localhost:2443/api/display" \
     -H 'ID: <redacted>' \
     -H 'Content-Type: application/json'
----

The {trmnl_firmware_link} will include the following headers in each HTTP request. All are optional except for the `ID` header. Here's the full list:

* `ACCESS_TOKEN`: The API key (or an empty string if not present).
* `BATTERY_VOLTAGE`: The remaining battery level. This is a float (usually 0.0 to 4.1).
* `FW_VERSION`: The firmware version (i.e. `1.2.3`).
* `HEIGHT`: :The device height. Example: 480.
* `HOST`: The host (usually the IP address).
* `ID`: The MAC address of the device.
* `MODEL`: The generic device model (doesn't match {trmnl_api_gem_link} model names but can be used as a fuzzy match).
* `REFRESH_RATE`: The current refresh rate as saved on the device. Example: 100.
* `RSSI`: The WiFi signal strength (usually -100 to 100).
* `USER_AGENT`: The device name (usually the ESP32 board name).
* `WIDTH`: The device width. Example: 800.

The above can be used to update your device settings upon each request.
====

.Response
[%collapsible]
====

The following is an example of the response sent back to the device which also how you can change the behavior of the device.

[source,json]
----
{
  "filename": "demo.bmp",
  "firmware_url": "http://localhost:2443/assets/firmware/1.4.8.bin",
  "firmware_version": "1.4.8",
  "image_url": "https://localhost:2443/assets/screens/A1B2C3D4E5F6/demo.bmp",
  "image_url_timeout": 0,
  "refresh_rate": 130,
  "reset_firmware": false,
  "special_function": "sleep",
  "update_firmware": false
}
----
====

=== Log

Used by device firmware to log information about your device. Mostly used for debugging purposes. You can find device specific logs within the UI by clicking on your device logs.

.Request
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/log" \
     -H 'ID: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "logs": [
    {
      "id": 666,
      "message": "An API test.",
      "wifi_status": "connected",
      "created_at": 1742022124,
      "sleep_duration": 31,
      "refresh_rate": 30,
      "free_heap_size": 160656,
      "max_alloc_size": 180000,
      "source_path": "src/bl.cpp",
      "wake_reason": "timer",
      "firmware_version": "1.5.2",
      "retry": 1,
      "battery_voltage": 4.772,
      "source_line": 597,
      "special_function": "none",
      "wifi_signal": -54
    }
  ]
}'
----
====

.Response
[%collapsible]
====
The server will process the payload, associate all records with the appropriate device, and answer a HTTP 204 status with no content.
====

=== Setup

Used for new device setup (auto-provisioning) only. The device still hit this endpoint but, once auto-provisioned, is ignored by the server.

.Request
[%collapsible]
====
[source,bash]
----
curl "https://localhost:2443/api/setup/" \
     -H 'ID: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.Response
[%collapsible]
====
[source,json]
----
{
  "api_key": "<redacted>",
  "friendly_id": "ABC123",
  "image_url": "https://localhost:2443/assets/setup.bmp",
  "message": "Welcome to TRMNL BYOS"
}
----
====

== Server

⚠️ *These endpoints are evolving. We do our best to minimize impact but please be aware action might be required on your part when new versions are released.*

These endpoints are unique to this server implementation and allow you to interact via your favorite JSON Data API client. The following features are supported:

* All endpoints require authentication using JWT tokens which is explained below.
* All error responses adhere to link:https://www.rfc-editor.org/rfc/rfc9457[RFC 9457 (Problem Details for HTTP APIs)] as implemented by the {petail_link} gem which allows you to quickly parse the error responses in your own application if desired.

=== Authentication

All server specific endpoints require authentication using JWT tokens as powered by the {rodauth_link} gem. The following explains how this works.

==== Login

To acquire the JWT token necessary for making API requests, you only need to send the following request to the login endpoint as follows:

[source,bash]
----
curl -X "POST" "https://localhost:2443/login" \
     -H 'Content-Type: application/json' \
     -d $'{
  "login": "<redacted>",
  "password": "<redacted>"
}'
----

The above will yield the following response:

[source,json]
----
{
  "access_token": "<redacted>",
  "refresh_token": "1_3_jm6ajAaXyUoaL6cdehXLPKRxvj9RJMmJecA_3p7lmj8",
  "success": "You have been logged in."
}
----

Your login (email) and password must be identical to what you supplied during the registration process via the Web UI.

==== Refresh Tokens

To refresh your `access_token` before it has expired (default: 30 minutes), you'll need to make an API request to the following endpoint:

[source,bash]
----
curl -X "POST" "https://localhost:2443/api/jwt" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "refresh_token": "<redacted>"
}'
----

The above will yield the following response:

[source,json]
----
{
  "refresh_token": "<redacted>",
  "access_token": "<redacted>"
}
----

With the above response in hand, you can now make new requests to refresh your access token by using the response's `access_token` for your authorization header along with the `refresh_token` for your payload body. A refresh token is valid for 14 days before expiring.

==== Configuration

If you wish to lengthen the amount of time before your JWT token expires, you can configure the `API_ACCESS_TOKEN_PERIOD` environment variable as documented in the link:/README.adoc#_configuration[Configuration].

=== Devices

Allows you to manage your devices.

.GET Request
[%collapsible]
====
[source,bash]
----
# All devices.
curl "https://localhost:2443/api/devices" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'

# Single device.
curl "https://localhost:2443/api/devices/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
# All devices.
{
  "data": [
    {
      "id": 1,
      "model_id": 1,
      "playlist_id": 1,
      "friendly_id": "DEMO11",
      "label": "Demo",
      "mac_address": "A1:B2:C3:D4:E5:F6",
      "api_key": "OScdcN0kFbKjFcid9Kz6Cx",
      "firmware_version": "1.5.12",
      "wifi": -71,
      "battery": 4.0,
      "refresh_rate": 500,
      "image_timeout": 0,
      "width": 800,
      "height": 480,
      "proxy": true,
      "firmware_update": true,
      "sleep_start_at": "22:30:00",
      "sleep_stop_at": "05:30:00",
      "created_at": "2025-07-29T16:19:05+0000",
      "updated_at": "2025-07-29T16:19:05+0000"
    }
  ]
}

# Single device.
{
  "data": {
    "id": 1,
    "model_id": 1,
    "playlist_id": 1,
    "friendly_id": "DEMO11",
    "label": "Demo",
    "mac_address": "A1:B2:C3:D4:E5:F6",
    "api_key": "OScdcN0kFbKjFcid9Kz6Cx",
    "firmware_version": "1.5.12",
    "wifi": -71,
    "battery": 4.0,
    "refresh_rate": 500,
    "image_timeout": 0,
    "width": 800,
    "height": 480,
    "proxy": true,
    "firmware_update": true,
    "sleep_start_at": "22:30:00",
    "sleep_stop_at": "05:30:00",
    "created_at": "2025-07-29T16:19:05+0000",
    "updated_at": "2025-07-29T16:19:05+0000"
  }
}
----

You'll get an empty array when no devices exist.
====

.POST Request
[%collapsible]
====
[source,bash]
----
# Minimum
curl -X "POST" "https://localhost:2443/api/devices" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "device": {
    "label": "Demo",
    "model_id": 1,
    "mac_address": "A1:B2:C3:D4:E5:F6"
  }
}'
----

[source,bash]
----
# Maximum (all possible fields)
curl -X "POST" "https://localhost:2443/api/devices" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "device": {
    "model_id": 1,
    "playlist_id": null,
    "label": "Demo",
    "friendly_id": "DEMO11",
    "mac_address": "A1:B2:C3:D4:E5:F6",
    "api_key": "OScdcN0kFbKjFcid9Kz6Cx",
    "refresh_rate": "500",
    "image_timeout": "0",
    "firmware_update": true,
    "proxy": true,
    "sleep_start_at": "23:00:00",
    "sleep_stop_at": "06:00:00"
  }
}'
----

====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "model_id": 1,
    "playlist_id": 1,
    "friendly_id": "DEMO11",
    "label": "Demo",
    "mac_address": "A1:B2:C3:D4:E5:F6",
    "api_key": "OScdcN0kFbKjFcid9Kz6Cx",
    "firmware_version": "1.5.12",
    "wifi": -71,
    "battery": 4.0,
    "refresh_rate": 500,
    "image_timeout": 0,
    "width": 800,
    "height": 480,
    "proxy": true,
    "firmware_update": true,
    "sleep_start_at": "22:30:00",
    "sleep_stop_at": "05:30:00",
    "created_at": "2025-07-29T16:19:05+0000",
    "updated_at": "2025-07-29T16:19:05+0000"
  }
}
----
====

.PATCH Request
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/devices/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "device": {
    "refresh_rate": 250
  }
}'
----

You can change a single attribute or multiple attributes at once.
====

.PATCH Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "model_id": 1,
    "playlist_id": 3,
    "friendly_id": "DEMO11",
    "label": "Demo",
    "mac_address": "A1:B2:C3:D4:E5:F6",
    "api_key": "OScdcN0kFbKjFcid9Kz6Cx",
    "firmware_version": "1.5.12",
    "wifi": -71,
    "battery": 4.0,
    "refresh_rate": 250,
    "image_timeout": 0,
    "width": 800,
    "height": 480,
    "proxy": true,
    "firmware_update": true,
    "sleep_start_at": "22:30:00",
    "sleep_stop_at": "05:30:00",
    "created_at": "2025-07-29T16:19:05+0000",
    "updated_at": "2025-07-29T16:19:05+0000"
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/devices/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{}'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "model_id": 1,
    "playlist_id": 3,
    "friendly_id": "DEMO11",
    "label": "Demo",
    "mac_address": "A1:B2:C3:D4:E5:F6",
    "api_key": "OScdcN0kFbKjFcid9Kz6Cx",
    "firmware_version": "1.5.12",
    "wifi": -71,
    "battery": 4.0,
    "refresh_rate": 500,
    "image_timeout": 0,
    "width": 800,
    "height": 480,
    "proxy": true,
    "firmware_update": true,
    "sleep_start_at": "22:30:00",
    "sleep_stop_at": "05:30:00",
    "created_at": "2025-07-29T16:19:05+0000",
    "updated_at": "2025-07-29T16:19:05+0000"
  }
}
----

You'll get an empty hash when there is nothing to delete.
====

=== Firmware

Manages firmware records for keeping devices up-to-date. By default, firmware is sourced from {trmnl_firmware_link} but you can manage your own custom firmware if desired. The following details the supported requests and responses.

.GET Request
[%collapsible]
====
[source,bash]
----
# All records.
curl "https://localhost:2443/api/firmware" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'

# Single record.
curl "https://localhost:2443/api/firmware/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
# All records.
{
  "data": [
    {
      "id": 1,
      "version": "1.7.2",
      "kind": "trmnl",
      "file_name": "1.7.2.bin",
      "mime_type": "application/octet-stream",
      "size": 1306608,
      "uri": "/uploads/60a5253edd0ab53cc31619a836c6cdb8.bin",
      "created_at": "2026-01-08T21:26:34+0000",
      "updated_at": "2026-01-08T21:26:34+0000"
    }
  ]
}

# Single record.
{
  "data": {
    "id": 1,
    "version": "1.7.2",
    "kind": "trmnl",
    "file_name": "1.7.2.bin",
    "mime_type": "application/octet-stream",
    "size": 1306608,
    "uri": "/uploads/60a5253edd0ab53cc31619a836c6cdb8.bin",
    "created_at": "2026-01-08T21:26:34+0000",
    "updated_at": "2026-01-08T21:26:34+0000"
  }
}
----

You'll get an empty array when no firmware exist.
====

.POST Request
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/firmware" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "firmware": {
    "version": "2.0.0",
    "kind": "terminus",
    "uri": "https://demo.terminus.io/2.0.0.bin"
  }
}'
----
====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 10,
    "version": "2.0.0",
    "kind": "terminus",
    "file_name": "2.0.0.bin",
    "mime_type": "application/octet-stream",
    "size": 1225536,
    "uri": "/uploads/0c2f5a1acb23d20e9f72828254c4f258.bin",
    "created_at": "2026-01-12T22:32:08+0000",
    "updated_at": "2026-01-12T22:32:09+0000"
  }
}
----
====

.PATCH Request
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/firmware/10" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "firmware": {
    "version": "2.0.0"
  }
}'
----

You can change a single attribute or multiple attributes at once.
====

.PATCH Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 10,
    "version": "2.0.0",
    "kind": "terminus",
    "file_name": "2.0.0.bin",
    "mime_type": "application/octet-stream",
    "size": 1225536,
    "uri": "/uploads/31c6151dfa9362053022a9bfcab5b2b5.bin",
    "created_at": "2026-01-12T22:32:08+0000",
    "updated_at": "2026-01-12T22:32:42+0000"
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/firmware/10" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{}'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 10,
    "version": "2.0.0",
    "kind": "terminus",
    "file_name": "2.0.0.bin",
    "mime_type": "application/octet-stream",
    "size": 1225536,
    "uri": "/uploads/31c6151dfa9362053022a9bfcab5b2b5.bin",
    "created_at": "2026-01-12T22:32:08+0000",
    "updated_at": "2026-01-12T22:32:42+0000"
  }
}
----

You'll get an empty hash when there is nothing to delete.
====

=== Models

Provides model information which is the core specification for devices and screens. Models are also differentiated by `kind` which can be:

* `trmnl`: Originates from our {core_link} server and is part of the synchronization process provided by the model link:/doc/jobs.adoc[Job].
* `terminus`: Originates from Terminus only.
* `+*+`: Additional types exist for custom devices such as Kindle, BYOD, and so forth.

The following provides details on all requests and responses.

.GET Request
[%collapsible]
====
[source,bash]
----
# All models.
curl "https://localhost:2443/api/models" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'

# Single model.
curl "https://localhost:2443/api/models/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
# All models.
{
  "data": [
    {
      "id": 1,
      "name": "og_png",
      "label": "TRMNL (1-bit)",
      "description": "TRMNL (1-bit)",
      "kind": "terminus",
      "mime_type": "image/png",
      "colors": 2,
      "bit_depth": 1,
      "rotation": 0,
      "offset_x": 0,
      "offset_y": 0,
      "width": 800,
      "height": 480,
      "created_at": "2025-08-13T19:34:08+0000",
      "updated_at": "2025-08-13T19:34:08+0000"
    }
  ]
}

# Single model.
{
  "data": {
    "id": 1,
    "name": "og_png",
    "label": "TRMNL (1-bit)",
    "description": "TRMNL (1-bit)",
    "kind": "terminus",
    "mime_type": "image/png",
    "colors": 2,
    "bit_depth": 1,
    "rotation": 0,
    "offset_x": 0,
    "offset_y": 0,
    "width": 800,
    "height": 480,
    "created_at": "2025-08-13T19:34:08+0000",
    "updated_at": "2025-08-13T19:34:08+0000"
  }
}
----

You'll get an empty array when no models exist.
====

.POST Request
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/models" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "model": {
    "name": "demo",
    "label": "Demo",
    "description": "A demonstration.",
    "kind": "terminus",
    "rotation": 25,
    "width": "1000",
    "colors": 4,
    "mime_type": "image/png",
    "bit_depth": 2,
    "offset_x": 50,
    "height": "500",
    "offset_y": 100,
    "created_at": "2025-08-13T19:34:08+0000",
    "updated_at": "2025-08-13T19:34:08+0000"
  }
}'
----
====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 12,
    "name": "demo",
    "label": "Demo",
    "description": "A demonstration.",
    "kind": "terminus",
    "mime_type": "image/png",
    "colors": 4,
    "bit_depth": 2,
    "rotation": 25,
    "offset_x": 50,
    "offset_y": 100,
    "width": 1000,
    "height": 500,
    "created_at": "2025-08-13T19:42:06+0000",
    "updated_at": "2025-08-13T19:42:06+0000"
  }
}
----
====

.PATCH Request
[%collapsible]
====
[source,bash]
----
curl -X "PUT" "https://localhost:2443/api/models/12" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "model": {
    "description": "A patch demonstration."
  }
}'
----

You can change a single attribute or multiple attributes at once.
====

.PATCH Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 12,
    "name": "demo",
    "label": "Demo",
    "description": "A patch demonstration.",
    "kind": "terminus",
    "mime_type": "image/png",
    "colors": 4,
    "bit_depth": 2,
    "rotation": 25,
    "offset_x": 50,
    "offset_y": 100,
    "width": 1000,
    "height": 500,
    "created_at": "2025-08-13T19:42:06+0000",
    "updated_at": "2025-08-13T19:42:31+0000"
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/models/2" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{}'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 12,
    "name": "demo",
    "label": "Demo",
    "description": "A patch demonstration.",
    "kind": "terminus",
    "width": 1000,
    "height": 500,
    "mime_type": "image/png",
    "colors": 4,
    "bit_depth": 2,
    "rotation": 25,
    "offset_x": 50,
    "offset_y": 100,
    "created_at": "2025-08-13 19:42:06 UTC",
    "updated_at": "2025-08-13 19:42:31 UTC"
  }
}
----

You'll get an empty hash when there is nothing to delete.
====

=== Playlists

Provides playlist information. The following provides details on all requests and responses.

.GET Request
[%collapsible]
====
[source,bash]
----
# All playlists
curl "https://localhost:2443/api/playlists" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'

# Single playlist.
curl "https://localhost:2443/api/playlists/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
# All playlists.
{
  "data": [
    {
      "id": 1,
      "name": "demo",
      "label": "Demo",
      "current_item_id": 39,
      "mode": "automatic",
      "created_at": "2026-03-05T00:14:56+0000",
      "updated_at": "2026-03-05T00:14:56+0000",
      "items": [
        {
          "id": 39,
          "screen_id": 15,
          "position": 1,
          "created_at": "2026-03-05T00:14:56+0000",
          "updated_at": "2026-03-05T00:14:56+0000"
        },
        {
          "id": 40,
          "screen_id": 16,
          "position": 2,
          "created_at": "2026-03-05T00:14:56+0000",
          "updated_at": "2026-03-05T00:14:56+0000"
        }
      ]
    }
  ]
}

# Single playlist.
{
  "data": {
    "id": 1,
    "name": "demo",
    "label": "Demo",
    "current_item_id": 39,
    "mode": "automatic",
    "created_at": "2026-03-05T00:14:56+0000",
    "updated_at": "2026-03-05T00:14:56+0000",
    "items": [
      {
        "id": 39,
        "screen_id": 15,
        "position": 1,
        "created_at": "2026-03-05T00:14:56+0000",
        "updated_at": "2026-03-05T00:14:56+0000"
      },
      {
        "id": 40,
        "screen_id": 16,
        "position": 2,
        "created_at": "2026-03-05T00:14:56+0000",
        "updated_at": "2026-03-05T00:14:56+0000"
      }
    ]
  }
}
----

You'll get an empty array when no playlists exist.
====

.POST Request
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/playlists" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "playlist": {
    "name": "demo",
    "label": "Demo",
    "items": [
      {
        "screen_id": "15"
      },
      {
        "screen_id": "16"
      }
    ]
  }
}'
----
====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "name": "demo",
    "label": "Demo",
    "current_item_id": 39,
    "mode": "automatic",
    "created_at": "2026-03-05T00:14:56+0000",
    "updated_at": "2026-03-05T00:14:56+0000",
    "items": [
      {
        "id": 39,
        "screen_id": 15,
        "position": 1,
        "created_at": "2026-03-05T00:14:56+0000",
        "updated_at": "2026-03-05T00:14:56+0000"
      },
      {
        "id": 40,
        "screen_id": 16,
        "position": 2,
        "created_at": "2026-03-05T00:14:56+0000",
        "updated_at": "2026-03-05T00:14:56+0000"
      }
    ]
  }
}
----
====

.PATCH Request
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/playlists/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "playlist": {
    "name": "update",
    "label": "Update",
    "mode": "manual",
    "items": [
      {
        "screen_id": "15"
      },
      {
        "screen_id": "16"
      }
    ]
  }
}'
----

You can change a single attribute or multiple attributes at once. Use an empty items array will delete all items in your playlist.
====

.PATCH Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "name": "update",
    "label": "Update",
    "current_item_id": null,
    "mode": "manual",
    "created_at": "2026-03-05T00:14:56+0000",
    "updated_at": "2026-03-05T00:26:44+0000",
    "items": [
      {
        "id": 51,
        "screen_id": 16,
        "position": 1,
        "created_at": "2026-03-05T00:26:44+0000",
        "updated_at": "2026-03-05T00:26:44+0000"
      },
      {
        "id": 52,
        "screen_id": 15,
        "position": 2,
        "created_at": "2026-03-05T00:26:44+0000",
        "updated_at": "2026-03-05T00:26:44+0000"
      }
    ]
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/playlists/2" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{}'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 11,
    "name": "update",
    "label": "Update",
    "current_item_id": null,
    "mode": "manual",
    "created_at": "2026-03-05T00:14:56+0000",
    "updated_at": "2026-03-05T00:26:44+0000",
    "items": [
      {
        "id": 51,
        "screen_id": 16,
        "position": 1,
        "created_at": "2026-03-05T00:26:44+0000",
        "updated_at": "2026-03-05T00:26:44+0000"
      },
      {
        "id": 52,
        "screen_id": 15,
        "position": 2,
        "created_at": "2026-03-05T00:26:44+0000",
        "updated_at": "2026-03-05T00:26:44+0000"
      }
    ]
  }
}
----

You'll get an empty hash when there is nothing to delete.
====

=== Screens

Used for managing device screens by supplying content for rendering, screenshotting, and grey scaling to render properly on your device. You can also use these optional keys when making requests:

* `playlist_id`: When supplied, ensures your screen is added to an existing playlist.
* `file_name`: When supplied, ensures your desired file name is used. Otherwise, if you don't supply a `file_name`, the server will generate one for you using a UUID for the file name.

.GET Request
[%collapsible]
====
[source,bash]
----
curl "https://localhost:2443/api/screens" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
{
  "data": [
    {
      "id": 3,
      "model_id": 1,
      "label": "Moon",
      "name": "plugin-6e6740",
      "created_at": "2025-07-29T16:29:02+0000",
      "updated_at": "2025-07-29T16:29:02+0000",
      "filename": "plugin-6e6740.bmp",
      "mime_type": "image/bmp",
      "bit_depth": 1,
      "width": 800,
      "height": 480,
      "size": 48062,
      "uri": "/uploads/9fb384c1aa9043ccfee781ab21d99aa0.bmp"
    }
  ]
}
----
====

.POST Request (HTML Content)
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/screens" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "model_id": "1",
    "label": "Demo",
    "name": "demo",
    "content": "<h1>Demo</h1>",
    "file_name": "demo.png"
  }
}'
----
====

.POST Request (Preprocessed URI)
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/screens" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "model_id": "1",
    "label": "Demo",
    "name": "demo",
    "uri": "https://leonardo.ai/wp-content/uploads/2023/07/image-131.jpeg",
    "preprocessed": true,
    "file_name": "demo.png"
  }
}'
----
====

.POST Request (Unprocessed URI)
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/screens" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "model_id": "1",
    "label": "Demo",
    "name": "demo",
    "uri": "https://leonardo.ai/wp-content/uploads/2023/07/image-131.jpeg",
    "file_name": "demo.png"
  }
}'
----
====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 13,
    "model_id": 1,
    "label": "Demo",
    "name": "demo",
    "created_at": "2025-07-29T19:06:04+0000",
    "updated_at": "2025-07-29T19:06:04+0000",
    "filename": "demo.png",
    "mime_type": "image/png",
    "bit_depth": 1,
    "width": 800,
    "height": 480,
    "size": 415,
    "uri": "/uploads/619415a00830fa630649706977e95302.png"
  }
}
----

No matter what parameters you use for this request, you'll always get a path (unless an error is encountered).
====

.PATCH Request (HTML Content)
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/screens/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "content": "<img src=\\"https://leonardo.ai/wp-content/uploads/2023/07/image-129.jpeg\\">"
  }
}'
----
====

.PATCH Request (Preprocessed URI)
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/screens/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "preprocessed": true,
    "uri": "https://demo.io/demo.png"
  }
}'
----
====

.PATCH Request (Unprocessed URI)
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/screens/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "preprocessed": true,
    "uri": "https://leonardo.ai/wp-content/uploads/2023/07/image-131.jpeg"
  }
}'
----
====

.PATCH Response
[%collapsible]
====
[source,bash]
----
{
  "data": {
    "id": 1,
    "model_id": 1,
    "label": "Demo",
    "name": "demo",
    "created_at": "2025-08-12T19:23:17+0000",
    "updated_at": "2025-08-12T19:23:17+0000",
    "filename": "demo.png",
    "mime_type": "image/png",
    "bit_depth": 1,
    "width": 800,
    "height": 480,
    "size": 462,
    "uri": "/uploads/71d0f2ec47b861ea8fe7807705d6e87b.png"
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/screens/13" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 13,
    "model_id": 1,
    "label": "Demo",
    "name": "demo",
    "created_at": "2025-07-29T19:11:04+0000",
    "updated_at": "2025-07-29T19:11:04+0000",
    "filename": "demo.png",
    "mime_type": "image/png",
    "bit_depth": 1,
    "width": 800,
    "height": 480,
    "size": 126,
    "uri": "/uploads/e27dc53657963e5ad765fdc246e60a3c.png"
  }
}
----
====

You'll notice the POST and PATCH requests allow you to supply different kinds of content. Here's how you can leverage each:

* *HTML Content*: Allows you to render custom HTML content as an image on your device. This includes CSS, JavaScript, and HTML. At a minimum, you'll want to use the following to prevent white borders appearing around your generated screens: `* { margin: 0; }`. Due to this being so flexible, this also means you can externally link and use our {trmnl_firmware_link} when building custom screens. You can also use the Designer, within the Terminus UI, to build custom screens in real-time for faster feedback. The result of your work can be supplied to this endpoint to create a new screen for display on your device.
* *Preprocessed URI*: Allows you to render a preprocessed image on your device. The `preprocessed` value must be `true` when supplied. This also assumes the image is fully compatible with the device in terms of greyscale, bit depth, color depth, and so forth. We _do not process this image_ and only cache the image locally for display on your device. If don't want this, and want your image to be fully processed, then see the Unprocessed URI documentation below.
* *Unprocessed URI*: Allows you to render a unprocessed image on your device. We'll automatically process the image for rendering on your device. The `dimensions` parameter is optional and defaults to `800x480` when not supplied. You can use the full {image_magick_geometry_link} syntax for this value.
