:toc: macro
:toclevels: 5
:figure-caption!:

:core_link: link:https://trmnl.com[Core]
:image_magick_geometry_link: link:https://www.imagemagick.org/script/command-line-processing.php#geometry[ImageMagick Geometry]
:petail_link: link:https://alchemists.io/projects/petail[Petail]
:rodauth_link: link:https://rodauth.jeremyevans.net[Rodauth]
:trmnl_api_gem_link: link:https://github.com/usetrmnl/trmnl-api[TRMNL API]
:trmnl_firmware_link: link:https://github.com/usetrmnl/trmnl-firmware[TRMNL Firmware]

= API

The API is divided into two categories: Firmware and Server. The former is more stable and mimics what we use on the {core_link} server. The latter is still in development and is unique to Terminus only. The following sections detail each.

toc::[]

== Firmware

The following endpoints are used to communicate with your device's {trmnl_firmware_link}. These endpoints typically require authentication via the HTTP `ID` header which is your device's MAC address. Any changes to these endpoints require updates to both the firmware and this implementation so they don't change often.

=== Display

Used for displaying new content on your device via a HTTP GET request. These requests happen on a scheduled interval as determined by the `refresh_rate` (see the response example below).

In truth, the design of this API request should have been a POST request but the {trmnl_firmware_link} only uses GET requests. The reason is because each request includes header information which provides device updates (such as WiFi signal strength, battery voltage, etc) that the server stores with the associated device. This means each request is an update from the device to the server while each response is a potential settings change from the server to the device.

.Request
[%collapsible]
====
[source,bash]
----
curl "https://localhost:2443/api/display" \
     -H 'ID: <redacted>' \
     -H 'Content-Type: application/json'
----

You can also use `ACCESS_TOKEN` but `ID` is recommended. Example:

[source,bash]
----
curl "https://localhost:2443/api/display" \
     -H 'ACCESS_TOKEN: <redacted>' \
     -H 'Content-Type: application/json'
----

The {trmnl_firmware_link} will include the following headers in each HTTP request. All are optional except for the `ID` header. Here's the full list:

* `ACCESS_TOKEN`: The device API when making Display API requests. Used by firmware and simulators to provision and authenticate a device.
* `BATTERY_CAPACITY`: Ratio of current and max battery capacity. Example: `11300/11420`.
* `BATTERY_CHARGING`: Boolean for if the battery is charging or not. Example: `0` or `1`.
* `BATTERY_COUNT`: The number batteries avaiable. Example: `2`.
* `BATTERY_CURRENT`: The battery current. Can be negative or positive. Example: `115`.
* `BATTERY_HEALTH`: The battery health. Range: `-1` to `100`.
* `BATTERY_TEMP`: The battery temperature in Celsius. Range: `-1` to infinity.
* `BATTERY_VOLTAGE`: The remaining battery level. This is a float (usually 0.0 to 4.1).
* `FW_VERSION`: The firmware version (i.e. `1.2.3`).
* `HEIGHT`: The device height. Example: 480.
* `HOST`: The host (usually the IP address).
* `ID`: The device MAC address. Example: `FE:68:44:CE:CA:C3`.
* `IMAGE_CACHED`: Boolean for if the image is cached on the device or not.
* `MODEL`: The generic device model (doesn't match {trmnl_api_gem_link} model names but can be used as a fuzzy match).
* `PERCENT_CHARGED`: The remaining charge of the device battery. When present, prefer this value over `BATTERY_VOLTAGE` because this will give you the exact percent of battery charge left.
* `REFRESH_RATE`: The current refresh rate as saved on the device. Example: 100.
* `RSSI`: The WiFi signal strength (usually -100 to 100).
* `SENSORS`: The sensor reasons for any sensors connected to the device.
* `TEMPERATURE_PROFILE`: The current profile applied for altering display behavior.
* `UPDATE_SOURCE`: The reason for why the device was woken from sleep.
* `USB_CONNECTED`: Boolean for if the USB power cable is connected or not.
* `WAKE_TIME`: The number of seconds the device was awake during the last cycle.
* `WIDTH`: The device width. Example: 800.

The above can be used to update your device settings upon each request.
====

.Response
[%collapsible]
====

The following is an example of the response sent back to the device which also how you can change the behavior of the device.

[source,json]
----
{
  "filename": "demo.png",
  "firmware_url": null,
  "firmware_version": null,
  "image_url": "http://192.168.0.13:2300/uploads/66584f02f7d0477b0b549efd234296e6.png",
  "image_url_timeout": 0,
  "maximum_compatibility": false,
  "refresh_rate": 900,
  "reset_firmware": false,
  "special_function": "none",
  "temperature_profile": "default",
  "touchbar_mode": "tap",
  "update_firmware": false
}
----
====

=== Log

Used by device firmware to log information about your device. Mostly used for debugging purposes. You can find device specific logs within the UI by clicking on your device logs.

.Request
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/log" \
     -H 'ID: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "logs": [
    {
      "id": 1,
      "message": "A test.",
      "wifi_status": "connected",
      "created_at": 1742022124,
      "sleep_duration": 31,
      "refresh_rate": 30,
      "free_heap_size": 160656,
      "max_alloc_size": 180000,
      "source_path": "src/bl.cpp",
      "level": "debug",
      "firmware_version": "1.8.6",
      "wake_reason": "timer",
      "retry": 1,
      "battery_voltage": 4.772,
      "source_line": 597,
      "special_function": "none",
      "wifi_signal": -54
    }
  ]
}'
----
====

.Response
[%collapsible]
====
The server will process the payload, associate all records with the appropriate device, and answer a HTTP 204 status with no content.
====

=== Setup

Used for new device setup (auto-provisioning) only. The device still hit this endpoint but, once auto-provisioned, is ignored by the server.

.Request
[%collapsible]
====
[source,bash]
----
curl "https://localhost:2443/api/setup" \
     -H 'ID: <redacted>' \
     -H 'Content-Type: application/json'
----

You can also use `ACCESS_TOKEN` but `ID` is recommended. Example:

[source,bash]
----
curl "https://localhost:2443/api/setup" \
     -H 'ACCESS_TOKEN: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.Response
[%collapsible]
====
[source,json]
----
{
  "api_key": "jiMMHN2kMSzpSi3n3bh4dmkNfgw5Z2",
  "image_url": "https://localhost:2443/assets/setup.bmp",
  "message": "Welcome to Terminus!",
  "status": 200
}
----
====

== Server

⚠️ *These endpoints are evolving. We do our best to minimize impact but please be aware action might be required on your part when new versions are released.*

These endpoints are unique to this server implementation and allow you to interact via your favorite JSON Data API client. The following features are supported:

* All endpoints require authentication using JWT tokens which is explained below.
* All error responses adhere to link:https://www.rfc-editor.org/rfc/rfc9457[RFC 9457 (Problem Details for HTTP APIs)] as implemented by the {petail_link} gem which allows you to quickly parse the error responses in your own application if desired.

=== Authentication

All server specific endpoints require authentication using JWT tokens as powered by the {rodauth_link} gem. The following explains how this works.

==== Login

To acquire the JWT token necessary for making API requests, you only need to send the following request to the login endpoint as follows:

[source,bash]
----
curl -X "POST" "https://localhost:2443/login" \
     -H 'Content-Type: application/json' \
     -d $'{
  "login": "<redacted>",
  "password": "<redacted>"
}'
----

The above will yield the following response:

[source,json]
----
{
  "access_token": "<redacted>",
  "refresh_token": "1_3_jm6ajAaXyUoaL6cdehXLPKRxvj9RJMmJecA_3p7lmj8",
  "success": "You have been logged in."
}
----

Your login (email) and password must be identical to what you supplied during the registration process via the Web UI.

==== Refresh Tokens

To refresh your `access_token` before it has expired (default: 30 minutes), you'll need to make an API request to the following endpoint:

[source,bash]
----
curl -X "POST" "https://localhost:2443/api/jwt" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "refresh_token": "<redacted>"
}'
----

The above will yield the following response:

[source,json]
----
{
  "refresh_token": "<redacted>",
  "access_token": "<redacted>"
}
----

With the above response in hand, you can now make new requests to refresh your access token by using the response's `access_token` for your authorization header along with the `refresh_token` for your payload body. A refresh token is valid for 14 days before expiring.

==== Configuration

If you wish to lengthen the amount of time before your JWT token expires, you can configure the `API_ACCESS_TOKEN_PERIOD` environment variable as documented in the link:/README.adoc#_configuration[Configuration].

=== Devices

Allows you to manage your devices.

.GET Request
[%collapsible]
====
[source,bash]
----
# All devices.
curl "https://localhost:2443/api/devices" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'

# Single device.
curl "https://localhost:2443/api/devices/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
# All devices.
{
  "data": [
    {
      "id": 1,
      "model_id": 11,
      "playlist_id": 1,
      "label": "Demo",
      "mac_address": "02:A1:B2:C3:D4:E5",
      "api_key": "jiMMHN2kMSzpSi3n3bh4dmkNfgw5Z2",
      "firmware_profile": true,
      "firmware_update": true,
      "firmware_version": "1.8.6",
      "wifi_band": 2.4,
      "wifi_signal": -64,
      "battery_charge": 0.0,
      "battery_voltage": 3.42,
      "charging": false,
      "refresh_rate": 900,
      "image_cached": false,
      "image_timeout": 0,
      "wake_reason": "timer",
      "wake_duration": 5591,
      "width": 800,
      "height": 480,
      "display_compatibility": false,
      "display_profile": "default",
      "command": "none",
      "touch_bar": "tap",
      "sleep_start_at": "18:00:00",
      "sleep_stop_at": "06:00:00",
      "synced_at": "2026-06-09T10:29:10-06:00",
      "created_at": "2026-05-17T16:36:58-06:00",
      "updated_at": "2026-06-09T10:29:10-06:00"
    }
  ]
}

# Single device.
{
  "data": {
    "id": 1,
    "model_id": 11,
    "playlist_id": 1,
    "label": "Demo",
    "mac_address": "02:A1:B2:C3:D4:E5",
    "api_key": "jiMMHN2kMSzpSi3n3bh4dmkNfgw5Z2",
    "firmware_profile": true,
    "firmware_update": true,
    "firmware_version": "1.8.6",
    "wifi_band": 2.4,
    "wifi_signal": -64,
    "battery_charge": 0.0,
    "battery_voltage": 3.42,
    "charging": false,
    "refresh_rate": 900,
    "image_cached": false,
    "image_timeout": 0,
    "wake_reason": "timer",
    "wake_duration": 5591,
    "width": 800,
    "height": 480,
    "display_compatibility": false,
    "display_profile": "default",
    "command": "none",
    "touch_bar": "tap",
    "sleep_start_at": "18:00:00",
    "sleep_stop_at": "06:00:00",
    "synced_at": "2026-06-09T10:29:10-06:00",
    "created_at": "2026-05-17T16:36:58-06:00",
    "updated_at": "2026-06-09T10:29:10-06:00"
  }
}
----

You'll get an empty array when no devices exist.
====

.POST Request
[%collapsible]
====
[source,bash]
----
# Minimum
curl -X "POST" "https://localhost:2443/api/devices" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "device": {
    "model_id": 1,
    "playlist_id": 1
  }
}'
----

[source,bash]
----
# Maximum (all possible fields)
curl -X "POST" "https://localhost:2443/api/devices" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "device": {
    "model_id": 11,
    "playlist_id": 1,
    "label": "Demo",
    "mac_address": "02:A1:B2:C3:D4:E5",
    "api_key": "jiMMHN2kMSzpSi3n3bh4dmkNfgw5Z2",
    "firmware_profile": true,
    "firmware_update": true,
    "firmware_version": "1.8.6",
    "wifi_band": 2.4,
    "wifi_signal": -64,
    "battery_charge": 0.0,
    "battery_voltage": 3.42,
    "charging": false,
    "refresh_rate": 900,
    "image_cached": false,
    "image_timeout": 0,
    "wake_reason": "timer",
    "wake_duration": 5591,
    "width": 800,
    "height": 480,
    "display_compatibility": false,
    "display_profile": "default",
    "command": "none",
    "touch_bar": "tap",
    "sleep_start_at": "18:00:00",
    "sleep_stop_at": "06:00:00",
    "synced_at": "2026-06-09T10:29:10-06:00",
    "created_at": "2026-05-17T16:36:58-06:00",
    "updated_at": "2026-06-09T10:29:10-06:00"
  }
}'
----

💡 If you don't need a playlist, you can supply `null` for the `playlist_id`.

💡 When the `mac_address` is not supplied, a locally administered (unicast) MAC address will be generated for you so you can experiment with a virtual device. If you don't want this behavior, ensure you supply the actual MAC address of your physical device.
====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "model_id": 11,
    "playlist_id": 1,
    "label": "Demo",
    "mac_address": "02:A1:B2:C3:D4:E5",
    "api_key": "jiMMHN2kMSzpSi3n3bh4dmkNfgw5Z2",
    "firmware_profile": true,
    "firmware_update": true,
    "firmware_version": "1.8.6",
    "wifi_band": 2.4,
    "wifi_signal": -64,
    "battery_charge": 0.0,
    "battery_voltage": 3.42,
    "charging": false,
    "refresh_rate": 900,
    "image_cached": false,
    "image_timeout": 0,
    "wake_reason": "timer",
    "wake_duration": 5591,
    "width": 800,
    "height": 480,
    "display_compatibility": false,
    "display_profile": "default",
    "command": "none",
    "touch_bar": "tap",
    "sleep_start_at": "18:00:00",
    "sleep_stop_at": "06:00:00",
    "synced_at": "2026-06-09T10:29:10-06:00",
    "created_at": "2026-05-17T16:36:58-06:00",
    "updated_at": "2026-06-09T10:29:10-06:00"
  }
}
----
====

.PATCH Request
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/devices/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "device": {
    "refresh_rate": 250,
    "sleep_start_at": "18:00:00",
    "sleep_stop_at": "06:00:00"
  }
}'
----

You can change a single attribute or multiple attributes at once. All attributes found in the POST request example are supported.
====

.PATCH Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "model_id": 11,
    "playlist_id": 1,
    "label": "Demo",
    "mac_address": "02:A1:B2:C3:D4:E5",
    "api_key": "jiMMHN2kMSzpSi3n3bh4dmkNfgw5Z2",
    "firmware_profile": true,
    "firmware_update": true,
    "firmware_version": "1.8.6",
    "wifi_band": 2.4,
    "wifi_signal": -64,
    "battery_charge": 0.0,
    "battery_voltage": 3.42,
    "charging": false,
    "refresh_rate": 250,
    "image_cached": false,
    "image_timeout": 0,
    "wake_reason": "timer",
    "wake_duration": 5591,
    "width": 800,
    "height": 480,
    "display_compatibility": false,
    "display_profile": "default",
    "command": "none",
    "touch_bar": "tap",
    "sleep_start_at": "18:00:00",
    "sleep_stop_at": "06:00:00",
    "synced_at": "2026-06-09T10:29:10-06:00",
    "created_at": "2026-05-17T16:36:58-06:00",
    "updated_at": "2026-06-09T10:29:10-06:00"
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/devices/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{}'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "model_id": 11,
    "playlist_id": 1,
    "label": "Demo",
    "mac_address": "02:A1:B2:C3:D4:E5",
    "api_key": "jiMMHN2kMSzpSi3n3bh4dmkNfgw5Z2",
    "firmware_profile": true,
    "firmware_update": true,
    "firmware_version": "1.8.6",
    "wifi_band": 2.4,
    "wifi_signal": -64,
    "battery_charge": 0.0,
    "battery_voltage": 3.42,
    "charging": false,
    "refresh_rate": 900,
    "image_cached": false,
    "image_timeout": 0,
    "wake_reason": "timer",
    "wake_duration": 5591,
    "width": 800,
    "height": 480,
    "display_compatibility": false,
    "display_profile": "default",
    "command": "none",
    "touch_bar": "tap",
    "sleep_start_at": "18:00:00",
    "sleep_stop_at": "06:00:00",
    "synced_at": "2026-06-09T10:29:10-06:00",
    "created_at": "2026-05-17T16:36:58-06:00",
    "updated_at": "2026-06-09T10:29:10-06:00"
  }
}
----

You'll get an empty hash when there is nothing to delete.
====

=== Firmware

Manages firmware records for keeping devices up-to-date. By default, firmware is sourced from {trmnl_firmware_link} but you can manage your own custom firmware if desired. The following details the supported requests and responses.

.GET Request
[%collapsible]
====
[source,bash]
----
# All records.
curl "https://localhost:2443/api/firmware" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'

# Single record.
curl "https://localhost:2443/api/firmware/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
# All records.
{
  "data": [
    {
      "id": 1,
      "version": "1.7.2",
      "kind": "trmnl",
      "file_name": "1.7.2.bin",
      "mime_type": "application/octet-stream",
      "size": 1306608,
      "uri": "/uploads/60a5253edd0ab53cc31619a836c6cdb8.bin",
      "created_at": "2026-01-08T21:26:34+00:00",
      "updated_at": "2026-01-08T21:26:34+00:00"
    }
  ]
}

# Single record.
{
  "data": {
    "id": 1,
    "version": "1.7.2",
    "kind": "trmnl",
    "file_name": "1.7.2.bin",
    "mime_type": "application/octet-stream",
    "size": 1306608,
    "uri": "/uploads/60a5253edd0ab53cc31619a836c6cdb8.bin",
    "created_at": "2026-01-08T21:26:34+00:00",
    "updated_at": "2026-01-08T21:26:34+00:00"
  }
}
----

You'll get an empty array when no firmware exist.
====

.POST Request
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/firmware" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "firmware": {
    "version": "2.0.0",
    "kind": "terminus",
    "uri": "https://demo.terminus.io/2.0.0.bin"
  }
}'
----
====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 10,
    "version": "2.0.0",
    "kind": "terminus",
    "file_name": "2.0.0.bin",
    "mime_type": "application/octet-stream",
    "size": 1225536,
    "uri": "/uploads/0c2f5a1acb23d20e9f72828254c4f258.bin",
    "created_at": "2026-01-12T22:32:08+00:00",
    "updated_at": "2026-01-12T22:32:09+00:00"
  }
}
----
====

.PATCH Request
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/firmware/10" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "firmware": {
    "version": "2.0.0"
  }
}'
----

You can change a single attribute or multiple attributes at once.
====

.PATCH Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 10,
    "version": "2.0.0",
    "kind": "terminus",
    "file_name": "2.0.0.bin",
    "mime_type": "application/octet-stream",
    "size": 1225536,
    "uri": "/uploads/31c6151dfa9362053022a9bfcab5b2b5.bin",
    "created_at": "2026-01-12T22:32:08+00:00",
    "updated_at": "2026-01-12T22:32:42+00:00"
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/firmware/10" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{}'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 10,
    "version": "2.0.0",
    "kind": "terminus",
    "file_name": "2.0.0.bin",
    "mime_type": "application/octet-stream",
    "size": 1225536,
    "uri": "/uploads/31c6151dfa9362053022a9bfcab5b2b5.bin",
    "created_at": "2026-01-12T22:32:08+00:00",
    "updated_at": "2026-01-12T22:32:42+00:00"
  }
}
----

You'll get an empty hash when there is nothing to delete.
====

=== Models

Provides model information which is the core specification for devices and screens. Models are also differentiated by `kind` which can be:

* `byod`, `kindle`, `tidybit`, `trmnl`: Originates from our {core_link} server and is part of the synchronization process provided by the model link:/doc/jobs.adoc[Job].
* `terminus`: Originates from Terminus only.
* `+*+`: Additional types exist for custom devices such as Kindle, BYOD, and so forth.

The following provides details on all requests and responses.

.GET Request
[%collapsible]
====
[source,bash]
----
# All models.
curl "https://localhost:2443/api/models" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'

# Single model.
curl "https://localhost:2443/api/models/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
# All models.
{
  "data": [
    {
      "default_palette_id": 1,
      "id": 1,
      "name": "v2",
      "label": "TRMNL X",
      "description": "TRMNL X",
      "kind": "trmnl",
      "mime_type": "image/png",
      "colors": 16,
      "bit_depth": 4,
      "rotation": 0,
      "offset_x": 0,
      "offset_y": 0,
      "scale_factor": 1.8,
      "css": {
        "classes": {
          "size": "screen--lg",
          "device": "screen--v2",
          "density": "screen--density-2x"
        },
        "variables": [
          [
            "--screen-w",
            "1040px"
          ],
          [
            "--screen-h",
            "780px"
          ],
          [
            "--pixel-ratio",
            "1.8"
          ],
          [
            "--dither-pixel-ratio",
            "2.0"
          ],
          [
            "--ui-scale",
            "1.0"
          ],
          [
            "--gap-scale",
            "1.0"
          ]
        ]
      },
      "width": 1872,
      "height": 1404,
      "created_at": "2026-02-12T15:57:28+00:00",
      "updated_at": "2026-04-01T20:09:35+00:00"
    }
  ]
}

# Single model.
"data": {
  "default_palette_id": 1,
  "id": 1,
  "name": "v2",
  "label": "TRMNL X",
  "description": "TRMNL X",
  "kind": "trmnl",
  "mime_type": "image/png",
  "colors": 16,
  "bit_depth": 4,
  "rotation": 0,
  "offset_x": 0,
  "offset_y": 0,
  "scale_factor": 1.8,
  "css": {
    "classes": {
      "size": "screen--lg",
      "device": "screen--v2",
      "density": "screen--density-2x"
    },
    "variables": [
      [
        "--screen-w",
        "1040px"
      ],
      [
        "--screen-h",
        "780px"
      ],
      [
        "--pixel-ratio",
        "1.8"
      ],
      [
        "--dither-pixel-ratio",
        "2.0"
      ],
      [
        "--ui-scale",
        "1.0"
      ],
      [
        "--gap-scale",
        "1.0"
      ]
    ]
  },
  "width": 1872,
  "height": 1404,
  "created_at": "2026-02-12T15:57:28+00:00",
  "updated_at": "2026-04-01T20:09:35+00:00"
}
----

You'll get an empty array when no models exist.
====

.POST Request
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/models" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "model": {
    "default_palette_id": 1,
    "name": "demo",
    "label": "Demo",
    "description": "A demonstration.",
    "mime_type": "image/png",
    "bit_depth": 2,
    "colors": 4,
    "css": {"classes" => {"size" => "screen--md"}},
    "scale_factor": 1.5,
    "rotation": 90,
    "offset_x": 10,
    "offset_y": 15,
    "width": 800,
    "height": 480
  }
}'
----

The `default_palette_id` key is optional. You can also use `nil` for the value to remove the default palette (although, using a default palette is recommended). At the moment, there isn't an API for palettes (this will be added in the future).
====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "default_palette_id": 1,
    "id": 1,
    "name": "demo",
    "label": "Demo",
    "description": "A demonstration.",
    "kind": "terminus",
    "mime_type": "image/png",
    "colors": 4,
    "bit_depth": 2,
    "rotation": 25,
    "offset_x": 10,
    "offset_y": 15,
    "scale_factor": 1.5,
    "css": {
      "classes": {
        "size": "screen-md"
      }
    },
    "width": 800,
    "height": 480,
    "created_at": "2026-04-01T23:55:12+00:00",
    "updated_at": "2026-04-01T23:55:12+00:00"
  }
}
----
====

.PATCH Request
[%collapsible]
====
[source,bash]
----
curl -X "PUT" "https://localhost:2443/api/models/12" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "model": {
    "description": "A patch."
  }
}'
----

You can change a single attribute or multiple attributes at once. All attributes as shown in the POST example are supported.
====

.PATCH Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "default_palette_id": nil,
    "id": 1,
    "name": "demo",
    "label": "Demo",
    "description": "A patch.",
    "kind": "terminus",
    "mime_type": "image/png",
    "colors": 4,
    "bit_depth": 2,
    "rotation": 25,
    "offset_x": 10,
    "offset_y": 15,
    "scale_factor": 1.5,
    "css": {
      "classes": {
        "size": "screen-md"
      }
    },
    "width": 800,
    "height": 480,
    "created_at": "2026-04-01T23:55:12+00:00",
    "updated_at": "2026-04-01T23:55:12+00:00"
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/models/2" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{}'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "default_palette_id": 1,
    "id": 1,
    "name": "demo",
    "label": "Demo",
    "description": "A demonstration.",
    "kind": "terminus",
    "mime_type": "image/png",
    "colors": 4,
    "bit_depth": 2,
    "rotation": 25,
    "offset_x": 10,
    "offset_y": 15,
    "scale_factor": 1.5,
    "css": {
      "classes": {
        "size": "screen-md"
      }
    },
    "width": 800,
    "height": 480,
    "created_at": "2026-04-01T23:55:12+00:00",
    "updated_at": "2026-04-01T23:55:12+00:00"
  }
}
----

You'll get an empty hash when there is nothing to delete.
====

=== Playlists

Provides playlist information. The following provides details on all requests and responses.

.GET Request
[%collapsible]
====
[source,bash]
----
# All playlists
curl "https://localhost:2443/api/playlists" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'

# Single playlist.
curl "https://localhost:2443/api/playlists/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
# All playlists.
{
  "data": [
    {
      "id": 1,
      "name": "demo",
      "label": "Demo",
      "current_item_id": 39,
      "mode": "automatic",
      "created_at": "2026-03-05T00:14:56+00:00",
      "updated_at": "2026-03-05T00:14:56+00:00",
      "items": [
        {
          "id": 39,
          "screen_id": 15,
          "position": 1,
          "created_at": "2026-03-05T00:14:56+00:00",
          "updated_at": "2026-03-05T00:14:56+00:00"
        },
        {
          "id": 40,
          "screen_id": 16,
          "position": 2,
          "created_at": "2026-03-05T00:14:56+00:00",
          "updated_at": "2026-03-05T00:14:56+00:00"
        }
      ]
    }
  ]
}

# Single playlist.
{
  "data": {
    "id": 1,
    "name": "demo",
    "label": "Demo",
    "current_item_id": 39,
    "mode": "automatic",
    "created_at": "2026-03-05T00:14:56+00:00",
    "updated_at": "2026-03-05T00:14:56+00:00",
    "items": [
      {
        "id": 39,
        "screen_id": 15,
        "position": 1,
        "created_at": "2026-03-05T00:14:56+00:00",
        "updated_at": "2026-03-05T00:14:56+00:00"
      },
      {
        "id": 40,
        "screen_id": 16,
        "position": 2,
        "created_at": "2026-03-05T00:14:56+00:00",
        "updated_at": "2026-03-05T00:14:56+00:00"
      }
    ]
  }
}
----

You'll get an empty array when no playlists exist.
====

.POST Request
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/playlists" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "playlist": {
    "name": "demo",
    "label": "Demo",
    "items": [
      {
        "screen_id": "15"
      },
      {
        "screen_id": "16"
      }
    ]
  }
}'
----
====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "name": "demo",
    "label": "Demo",
    "current_item_id": 39,
    "mode": "automatic",
    "created_at": "2026-03-05T00:14:56+00:00",
    "updated_at": "2026-03-05T00:14:56+00:00",
    "items": [
      {
        "id": 39,
        "screen_id": 15,
        "position": 1,
        "created_at": "2026-03-05T00:14:56+00:00",
        "updated_at": "2026-03-05T00:14:56+00:00"
      },
      {
        "id": 40,
        "screen_id": 16,
        "position": 2,
        "created_at": "2026-03-05T00:14:56+00:00",
        "updated_at": "2026-03-05T00:14:56+00:00"
      }
    ]
  }
}
----
====

.PATCH Request
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/playlists/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "playlist": {
    "name": "update",
    "label": "Update",
    "mode": "manual",
    "items": [
      {
        "screen_id": "15"
      },
      {
        "screen_id": "16"
      }
    ]
  }
}'
----

You can change a single attribute or multiple attributes at once. Use an empty items array will delete all items in your playlist.
====

.PATCH Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 1,
    "name": "update",
    "label": "Update",
    "current_item_id": null,
    "mode": "manual",
    "created_at": "2026-03-05T00:14:56+00:00",
    "updated_at": "2026-03-05T00:26:44+00:00",
    "items": [
      {
        "id": 51,
        "screen_id": 16,
        "position": 1,
        "created_at": "2026-03-05T00:26:44+00:00",
        "updated_at": "2026-03-05T00:26:44+00:00"
      },
      {
        "id": 52,
        "screen_id": 15,
        "position": 2,
        "created_at": "2026-03-05T00:26:44+00:00",
        "updated_at": "2026-03-05T00:26:44+00:00"
      }
    ]
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/playlists/2" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{}'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 11,
    "name": "update",
    "label": "Update",
    "current_item_id": null,
    "mode": "manual",
    "created_at": "2026-03-05T00:14:56+00:00",
    "updated_at": "2026-03-05T00:26:44+00:00",
    "items": [
      {
        "id": 51,
        "screen_id": 16,
        "position": 1,
        "created_at": "2026-03-05T00:26:44+00:00",
        "updated_at": "2026-03-05T00:26:44+00:00"
      },
      {
        "id": 52,
        "screen_id": 15,
        "position": 2,
        "created_at": "2026-03-05T00:26:44+00:00",
        "updated_at": "2026-03-05T00:26:44+00:00"
      }
    ]
  }
}
----

You'll get an empty hash when there is nothing to delete.
====

=== Screens

Used for managing device screens by supplying content for rendering, screenshotting, and grey scaling to render properly on your device. You can also use these optional keys when making requests:

* `playlist_id`: Ensures your screen is added to an existing playlist.
* `mode`: Determines the mode in which the screen will be processed. Default: `nil`. The following values are supported:
** `dither`: Ensures your image will be dithered. Useful when processing photos or images with very little text.
* `file_name`: Ensures your desired file name is used. Otherwise, when not supplied, the server will generate a UUID for the file name.

.GET Request
[%collapsible]
====
[source,bash]
----
curl "https://localhost:2443/api/screens" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.GET Response
[%collapsible]
====
[source,json]
----
{
  "data": [
    {
      "id": 3,
      "model_id": 1,
      "label": "Moon",
      "name": "plugin-6e6740",
      "created_at": "2025-07-29T16:29:02+00:00",
      "updated_at": "2025-07-29T16:29:02+00:00",
      "filename": "plugin-6e6740.bmp",
      "mime_type": "image/bmp",
      "bit_depth": 1,
      "width": 800,
      "height": 480,
      "size": 48062,
      "uri": "/uploads/9fb384c1aa9043ccfee781ab21d99aa0.bmp"
    }
  ]
}
----
====

.POST Request (HTML Content)
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/screens" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "model_id": "1",
    "label": "Demo",
    "name": "demo",
    "content": "<h1>Demo</h1>",
    "file_name": "demo.png"
  }
}'
----
====

.POST Request (Preprocessed URI)
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/screens" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "model_id": "1",
    "label": "Demo",
    "name": "demo",
    "uri": "https://leonardo.ai/wp-content/uploads/2023/07/image-131.jpeg",
    "preprocessed": true,
    "file_name": "demo.png"
  }
}'
----
====

.POST Request (Unprocessed URI)
[%collapsible]
====
[source,bash]
----
curl -X "POST" "https://localhost:2443/api/screens" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "model_id": "1",
    "label": "Demo",
    "name": "demo",
    "uri": "https://leonardo.ai/wp-content/uploads/2023/07/image-131.jpeg",
    "file_name": "demo.png"
  }
}'
----
====

.POST Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 13,
    "model_id": 1,
    "label": "Demo",
    "name": "demo",
    "created_at": "2025-07-29T19:06:04+00:00",
    "updated_at": "2025-07-29T19:06:04+00:00",
    "filename": "demo.png",
    "mime_type": "image/png",
    "bit_depth": 1,
    "width": 800,
    "height": 480,
    "size": 415,
    "uri": "/uploads/619415a00830fa630649706977e95302.png"
  }
}
----

No matter what parameters you use for this request, you'll always get a path (unless an error is encountered).
====

.PATCH Request (HTML Content)
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/screens/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "content": "<img src=\\"https://leonardo.ai/wp-content/uploads/2023/07/image-129.jpeg\\">"
  }
}'
----
====

.PATCH Request (Preprocessed URI)
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/screens/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "preprocessed": true,
    "uri": "https://demo.io/demo.png"
  }
}'
----
====

.PATCH Request (Unprocessed URI)
[%collapsible]
====
[source,bash]
----
curl -X "PATCH" "https://localhost:2443/api/screens/1" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json' \
     -d $'{
  "screen": {
    "preprocessed": true,
    "uri": "https://leonardo.ai/wp-content/uploads/2023/07/image-131.jpeg"
  }
}'
----
====

.PATCH Response
[%collapsible]
====
[source,bash]
----
{
  "data": {
    "id": 1,
    "model_id": 1,
    "label": "Demo",
    "name": "demo",
    "created_at": "2025-08-12T19:23:17+00:00",
    "updated_at": "2025-08-12T19:23:17+00:00",
    "filename": "demo.png",
    "mime_type": "image/png",
    "bit_depth": 1,
    "width": 800,
    "height": 480,
    "size": 462,
    "uri": "/uploads/71d0f2ec47b861ea8fe7807705d6e87b.png"
  }
}
----
====

.DELETE Request
[%collapsible]
====
[source,bash]
----
curl -X "DELETE" "https://localhost:2443/api/screens/13" \
     -H 'Authorization: <redacted>' \
     -H 'Content-Type: application/json'
----
====

.DELETE Response
[%collapsible]
====
[source,json]
----
{
  "data": {
    "id": 13,
    "model_id": 1,
    "label": "Demo",
    "name": "demo",
    "created_at": "2025-07-29T19:11:04+00:00",
    "updated_at": "2025-07-29T19:11:04+00:00",
    "filename": "demo.png",
    "mime_type": "image/png",
    "bit_depth": 1,
    "width": 800,
    "height": 480,
    "size": 126,
    "uri": "/uploads/e27dc53657963e5ad765fdc246e60a3c.png"
  }
}
----
====

You'll notice the POST and PATCH requests allow you to supply different kinds of content. Here's how you can leverage each:

* *HTML Content*: Allows you to render custom HTML content as an image on your device. This includes CSS, JavaScript, and HTML. At a minimum, you'll want to use the following to prevent white borders appearing around your generated screens: `* { margin: 0; }`. Due to this being so flexible, this also means you can externally link and use our {trmnl_firmware_link} when building custom screens. You can also use Desigs, within the Terminus UI, to build custom screens in real-time for faster feedback. The result of your work can be supplied to this endpoint to create a new screen for display on your device.
* *Preprocessed URI*: Allows you to render a preprocessed image on your device. The `preprocessed` value must be `true` when supplied. This also assumes the image is fully compatible with the device in terms of greyscale, bit depth, color depth, and so forth. We _do not process this image_ and only cache the image locally for display on your device. If don't want this, and want your image to be fully processed, then see the Unprocessed URI documentation below.
* *Unprocessed URI*: Allows you to render a unprocessed image on your device. We'll automatically process the image for rendering on your device. The `dimensions` parameter is optional and defaults to `800x480` when not supplied. You can use the full {image_magick_geometry_link} syntax for this value.
