:toc: macro
:toclevels: 5
:figure-caption!:

:doc_docker_link: link:https://github.com/usetrmnl/terminus/blob/main/doc/docker.adoc[Docker]
:doc_extensions_link: link:https://github.com/usetrmnl/terminus/blob/main/doc/extensions.adoc[Extensions]
:doc_jobs_link: link:https://github.com/usetrmnl/terminus/blob/main/doc/jobs.adoc[Jobs]
:doc_raspberry_pi_link: link:https://github.com/usetrmnl/terminus/blob/main/doc/raspberry_pi.adoc[Raspberry PI]
:ferrum_link: link:https://ferrum.rubycdp.com[Ferrum]
:http_link: link:https://github.com/httprb/http[HTTP]
:postgres_link: link:https://www.postgresql.org[PostgreSQL]
:puma_link: link:https://puma.io[Puma]
:rack_attack_link: link:https://github.com/rack/rack-attack[Rack Attack]
:trmnl_framework_link: link:https://trmnl.com/framework[TRMNL Framework]

= Configuration

The following explains how to customize this application further if desired.

== Environment Variables

There are several environment variables you can use to customize behavior by updating the `.env` file created for you during setup. They are:

* `API_ACCESS_TOKEN_PERIOD`: The amount of time, in seconds, the JWT access token remains valid before needing to refresh your access token. Useful when using the link:doc/api.adoc[Server APIs]. Your access token is directly tied to your session which means you'll need to set your `SESSION_LIFETIME_LIMIT` to the same value when making adjustments (especially if your `SESSION_LIFETIME_LIMIT` is lower than this value). You might also want to adjust your `SESSION_INACTIVITY_LIMIT` because your access token will expire if inactive for long periods of time too. Default: 1,800 seconds (30 minutes).
* `APP_SECRET`: Used for session, cookie, and Cross-Site Request Forgery (CSRF) protection. This is automatically created for you during setup but is recommended that you update this with your own secure value.
* `APP_SETUP`: Runs setup/update steps (i.e. asset compilation, database migrations, etc). Used by Docker only via the `entrypoint` script. Default: `nil` but `true` for the web service.
* `API_URI`: Used for connecting your device to this server or via link:doc/docker.adoc[Docker]. Defaults to your host machine's IP address and port. This assumes you are connecting your device directly to the same server Terminus is running on. If this is not the case and you are using a reverse proxy, DNS, or any service/layer between your device and Terminus then you need to update this value to be your host. For example, if your host is `http://demo.io` then this value must be `http://demo.io`. This includes updating your device, via the TRMNL captive Wifi portal, to use `http://demo.io` as your custom host too. How you configure `http://demo.io` to resolve to the server you are running Terminus on is up to you. All your device (and this value) cares about is what the external host (or IP and port) is for the device to make API requests too (they must be identical).
* `CERTIFICATE_URLS`: Defines a comma-separated list of CA certificate URLs which will be automatically installed as trusted certificates. Example: `"https://example.io/ca1.crt,https://example.org/ca2.pem"` Used by {doc_docker_link} only.
* `DATABASE_NAME`: Defines your database name. Used by {doc_docker_link} only. Default: `terminus`.
* `DATABASE_PASSWORD`: Defines your database password. Used by {doc_docker_link} only. Default: (auto-generated for you during setup).
* `DATABASE_PORT`: Defines your database port. Used by {doc_docker_link} only. Default: `5432`.
* `DATABASE_URL`: Defines the full URL based on the `+DATABASE_*+` settings. This is automatically configured for you during setup. See your `+.env*+` files for details.
* `DATABASE_URL`: Necessary to connect to your {postgres_link} database. Can be customized by changing the value in the `.env.development` or `.env.test` file created when you ran `bin/setup`.
* `DATABASE_USER`: Defines your database user. Used by {doc_docker_link} only. Default: `terminus`.
* `FERRUM_DEFAULT_TIMEOUT`: Used for configuring {ferrum_link} headless browser default time allowed for the browser to respond to a request. Default: `30`.
* `FERRUM_PROCESS_TIMEOUT`: Used for configuring {ferrum_link} headless browser time allowed for the browser to start. Default: `15`.
* `FERRUM_JAVASCRIPT_ERRORS`: Used for configuring {ferrum_link} headless browser JavaScript errors. Default: `true`.
* `FIRMWARE_SYNCHRONIZER`: Enables/disables firmware synchronization. See {doc_jobs_link} for details. Defaults to enabled.
* `FONT_SYNCHRONIZER`: Enables/disables firmware synchronization. See {doc_jobs_link} for details. Defaults to enabled.
* `FONTS_PATH`: The path to where {trmnl_framework_link} fonts are stored since the Framework stylesheets require a relative path to all fonts to load properly. This is necessary when rendering screens for {doc_extensions_link}. Default: `public/fonts`.
* `HANAMI_MAX_THREADS`: The maximum number of threads allowed for {puma_link}. Default: `5`.
* `HANAMI_MIN_THREADS`: The minimum number of threads allowed for {puma_link}. Default: `HANAMI_MAX_THREADS`.
* `HANAMI_WEB_CONCURRENCY`: The number of {puma_link} workers. Default: `0`.
* `HANAMI_PORT`: The default port when running the app locally or via {doc_docker_link}. When using Docker, this is used for the internal and external port mapping.
* `HTTP_TIMEOUT_CONNECT`: The time, in seconds, before HTTP times out when establishing a connection. Default: `2`.
* `HTTP_TIMEOUT_READ`: The time, in seconds, before HTTP times out when reading from a connection. Default: `10`.
* `HTTP_TIMEOUT_WRITE`: The time, in seconds, before HTTP times out when writing to a connection. Default: `10`.
* `KEYVALUE_DATABASE`: Defines your database ID. Used by {doc_docker_link} only. Default: `0`.
* `KEYVALUE_PASSWORD`: Defines your password. Used by {doc_docker_link} only. Default: (auto-generated for you during setup).
* `KEYVALUE_PORT`: Defines your port. Used by {doc_docker_link} only. Default: `6379`.
* `KEYVALUE_URL`: Defines the full URL based on the above `+KEYVALUE_*+` settings. This is automatically configured for you during setup. See your `+.env*+` files for details.
* `MODEL_SYNCHRONIZER`: Enables/disables model synchronization. See {doc_jobs_link} for details. Defaults to enabled.
* `RACK_ATTACK_ALLOWED_SUBNETS`: Defines the {rack_attack_link} subnets that are allowed to connect to this server which helps when adding DNS, a reverse proxy, or a VPN, etc. between your device and this application so you can use this environment variable to add more subnets as desired. This takes a single subnet/IP or an array -- with no spaces -- of subnets/IPs as values. Example: "111.111.111.111,150.120.0.0/16". Alternatively, you can disable Rack Attack altogether by removing the `config.middleware.use Rack::Attack` line from `config/app.rb` or customize Rack Attack via the `config/initializers/rack_attack.rb` file. Any of these approaches will allow you to get your service layer properly configured so your device can talk to this server. By default, the following subnets are allowed: `10.0.0.0/8`, `172.16.0.0/12`, `192.168.0.0/16`, `127.0.0.1`, and `::1`.
* `SENSORS_PATH`: The path to where sensor information is written. See {doc_raspberry_pi_link} for details. Default: `public/sensors.json`.
* `SCREEN_SYNCHRONIZER`: Enables/disables device proxied screen synchronization. See {doc_jobs_link} for details. Defaults to enabled.
* `SESSION_EXPIRATION_ENABLED`: Determines if your browser session or JWT API token is expired or not. A warning is logged when disabled because this bypasses all checks but can be useful on local networks that only you have access to. Default: `true`.
* `SESSION_INACTIVITY_LIMIT`: The amount of time, in seconds, since last browser session activity before needing to login again. This is checked _before_ `SESSION_LIFETIME_LIMIT`. Default: 1,800 seconds (30 minutes).
* `SESSION_LIFETIME_LIMIT`: The maximum time, in seconds, the browser session remains active -- including session activity -- before needing to login again. This is checked _after_ `SESSION_INACTIVITY_LIMIT`. Default: 86,400 seconds (1 day).

💡 The {http_link} gem is used for all HTTP requests via synchronization jobs, extensions, etc. Use the `+HTTP_*+` environment variables to customize link:https://github.com/httprb/http/wiki/Timeouts[timeout] behavior as desired.
