:toc: macro
:toclevels: 5
:figure-caption!:

:core_link: link:https://trmnl.com[Core]
:firmware_link: link:https://github.com/usetrmnl/trmnl-firmware[Firmware]
:framework_link: link:https://trmnl.com/framework[Framework]
:liquid_link: link:https://shopify.github.io/liquid/[Liquid]
:rfc_2626_link: link:https://www.rfc-editor.org/rfc/rfc822[RFC 2616]
:trmnl_liquid_gem_link: link:https://github.com/usetrmnl/trmnl-liquid[TRMNL Liquid]
:trmnl_sensor_scanner_link: link:https://github.com/usetrmnl/sensor_scanner[Sensor Scanner]

= Extensions

Extensions are similar to Plugins as found in our {core_link} application. With extensions, the goal is to encompass all plugin capabilities under a single umbrella. This also fits better with the architecture of this application and allows this application to expand upon what is possible.

toc::[]

== Roadmap

The following provides a visual roadmap of current development and work that is scheduled to be completed in the future.

*Legend*

* ⚪️ Planned.
* 🟢 Supported.

*Features*

[options="header"]
|===
|                          | Status
| Native                   | ⚪️
| Private                  | 🟢
| Public                   | 🟢
| Third Party              | ⚪️
| Recipes                  | 🟢
| Import/Export (Core)     | ⚪️
| Import/Export (Terminus) | ⚪️
|===

== Walkthrough

To help you get started, let's walk through a scenario building an extension:

. Visit the _Extensions_ page and click the plus icon to create a new extension.
. Fill in _Label_ and _Name_ information.
. Select _TRMNL OG (2-bit)_ as your model (via the Build Matrix).
. For _Kind_, select _Poll_.
. For _URLs_, enter: `https://ghibliapi.vercel.app/films`.
. Scroll down to the Template editor, copy and paste the same Liquid Template (see below) but place it inside the `+<div class="layout layout--col">+` element.
. Click _Save_ to save your changes.
. Upon page reload, click the _Preview_ button to see how your screen will render.

.Liquid Template
[%collapsible]
====
[source,html]
----
{% for film in source limit:5 %}
  <div class="item">
    <div class="meta">
      <span class="index">{{ forloop.index }}</span>
    </div>

    <img src="{{film.image}}" width="50" height="50">

    <div class="content">
      <span class="title title--small">{{ film.title }}</span>
      <span class="description">{{ film.description | truncate: 100}}</span>
    </div>
  </div>
{% endfor %}
----
====

At this point, you can set a schedule for updating your screen as fast as a minute or as slow as a month.

== Liquid Templates

All extensions use {liquid_link} templates which allows you to format and style raw data into HTML for rendering as a screen. This includes default functionality and enhanced functionality as provided by the {trmnl_liquid_gem_link} gem.

== Schedules

By default, extensions have no schedule. This allows you to experiment building out your extension before you are ready to schedule when it should automatically render new screens. Once set, look for the screen(s) that are generated from your extension and then add them to your device playlist(s).

Your screen will constantly be updated, per your extension's schedule, for display on your device as dictated by your device's playlist.

== Build Matrix

The build matrix is a powerful extension feature which allows you to apply your responsive {framework_link} design for rendering on multiple models. To use, select all models you want your extension to build screens for and they will show up in the _Screens_ UI which you can add to your device playlists as desired. This is also why the Liquid template scaffold is provided for you and why you see `{{model.bit_depth}}` and other attributes available to you. This is because model information is dynamically supplied to your Liquid template when rendering a screen which allows you to build for multiple models at once.

== Sensors

If you'd like to leverage sensor information, there are two ways to do this. Each is described in the sections below.

=== Device

⚠️ Terminus supports acquiring sensors readings from sensors connected to your devices but a new {firmware_link} version is still required for full support. There is a Firmware feature branch in the works that, once folded in, will close the loop on this feature.

Once sensors are attached to your devices, Terminus will immediately capture this information for rendering in your Liquid templates.

Behind the scenes, your device will automatically include the `HTTP_SENSORS` header which adheres to {rfc_2626_link} when making a `/api/display` request with content similar to the following:

[source]
----
HTTP_SENSORS: make=Sensirion;model=SCD41;kind=carbon_dioxide;value=405;unit=ppm;created_at=1770850256,make=Sensirion;model=SCD41;kind=temperature;value=20.10;unit=celcius;created_at=1770850256
----

The above breaks down as follows:

* *Comma* (`,`): Delimits each record.
* *Semicolon* (`;`): Delimits each attribute within the record.
* *Equals* (`=`): Delimits each attribute key/value pair.

This allows each device to answer an empty array, a single record, or multiple records. All of this is saved in the database as sensor records for which you can access when building extensions. In the future, an HTTP POST request will be used for `/api/display` to prevent HTTP header length limits.

=== Server

You can attach sensors to your Raspberry PI which allows you to access sensor records when building extensions. This is fully explained in the link:/doc/raspberry_pi.adoc[Raspberry Pi Documentation] for this project.

== Import/Export

The ability to import and export extensions is the next major feature to tackle. The goal is to allow you to import and export Terminus extensions along with the import and export of {core_link} plugins. The translation of Core plugins will be handled for you automatically. In the meantime, you can use the above _Walkthrough_ to do this manually.
