firmware_synchronizer:
  class: Terminus::Jobs::Synchronizers::Firmware
  cron: "0 */6 * * *"
  description: "Synchronizes TRMNL Firmware."
font_synchronizer:
  class: Terminus::Jobs::Synchronizers::Font
  cron: "0 0 */1 * *"
  description: "Synchronizes TRMNL Framework fonts."
model_synchronizer:
  class: Terminus::Jobs::Synchronizers::Model
  cron: "0 0 */1 * *"
  description: "Synchronizes TRMNL models."
screen_synchronizer:
  class: Terminus::Jobs::Synchronizers::Screen
  cron: "0/5 * * * *"
  description: "Synchronizes TRMNL proxied device screen updates."
sensor_synchronizer:
  class: Terminus::Jobs::Synchronizers::Sensor
  cron: "0/1 * * * *"
  description: "Synchronizes server hosted sensor data (if any)."
